services:
  db:
    image: postgis/postgis:16-3.5-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "/opt/make-open-data-db/postgres/mount:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"

